### ISSUE TITLE
放在listview中出错

### ISSUE THREAD

**Issue by myface-wang** [llxdaxia/MultiView#2]
listview中第一个view显示不正常，就算只有一张图片也会显示9个。
此时log输出getview被绘制了两次
10-25 16:16:43.239 25255-25255/com.diecolor.rendezvous I/asd: listBean.getData()3
10-25 16:16:43.245 25255-25255/com.diecolor.rendezvous I/RestHttp: memory cache size : 33554432
10-25 16:16:43.259 25255-25255/com.diecolor.rendezvous I/RestHttp: [Get compress picture from diskCache]
10-25 16:16:43.265 25255-25255/com.diecolor.rendezvous I/RestHttp: [Get compress picture from diskCache]
10-25 16:16:43.265 25255-25255/com.diecolor.rendezvous I/RestHttp: [Get compress picture from memoryCache]
10-25 16:16:43.267 25255-25255/com.diecolor.rendezvous I/MultiView: onMeasure
10-25 16:16:43.267 25255-25255/com.diecolor.rendezvous I/MultiView: fuck--widthMode
10-25 16:16:43.268 25255-25255/com.diecolor.rendezvous I/asd: listBean.getData()3
10-25 16:16:43.269 25255-25255/com.diecolor.rendezvous I/RestHttp: [Get compress picture from memoryCache]
10-25 16:16:43.269 25255-25255/com.diecolor.rendezvous I/RestHttp: [Get compress picture from memoryCache]
10-25 16:16:43.269 25255-25255/com.diecolor.rendezvous I/RestHttp: [Get compress picture from memoryCache]
10-25 16:16:43.270 25255-25255/com.diecolor.rendezvous I/MultiView: onMeasure
10-25 16:16:43.270 25255-25255/com.diecolor.rendezvous I/MultiView: fuck--widthMode
10-25 16:16:43.270 25255-25255/com.diecolor.rendezvous I/MultiView: onLayout

**Comment by zhazhaxin** [comment]
我用RecyclerView时没发现这问题。
