### ISSUE TITLE
listview还是RecycleView，真心是会绘制2次

### ISSUE THREAD

**Issue by baoziguo** [llxdaxia/MultiView#3]
然后呢，你可以下拉刷新下，MultiView会类似于复用item那样，加载其他item里的图片~无限刷新，MultiView里装图片的list会无限add，瞬间一大波的图~

**Comment by zhazhaxin** [comment]
不是很懂你的意思，能看看你写得源代码吗

**Comment by baoziguo** [comment]
@Override
    public void onBindViewHolder(MyViewHolder myViewHolder, int i) {
        final Post post = mListData.get(i);
        runEnterAnimation(myViewHolder.itemView, i);
        if (TextUtils.isEmpty(post.getAuthor().getAvatar())){
            myViewHolder.iv_head.setTextAndColor(post.getAuthor().getUsername().substring(0, 1), Utils.generateBeautifulColor());
        }else {
            ImageLoader.getInstance().displayImage(post.getAuthor().getAvatar(), myViewHolder.iv_head);
        }
        myViewHolder.tv_content.setText(post.getContent());
        String imageUrl = post.getImageUrl();
        List<ImageBean> imageBeen = GsonUtil.jsonToList(imageUrl, ImageBean.class);
        for (int j = 0; j < imageBeen.size(); j++) {
            data.add(imageBeen.get(j).getImageUrl());
        }

//        Ion.with(myViewHolder.iv_img)
//                .load("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1489585575324&di=d70a13be31e38a309cf76414bb2e0b6a&imgtype=0&src=http%3A%2F%2Fe.hiphotos.baidu.com%2Fzhidao%2Fpic%2Fitem%2F359b033b5bb5c9eac939425fd239b6003bf3b340.jpg");
//        data.add("http://img2.imgtn.bdimg.com/it/u=1129872862,2532778270&fm=23&gp=0.jpg");
//        data.add("http://img4.imgtn.bdimg.com/it/u=3460036485,2448243983&fm=23&gp=0.jpg");
//        data.add("http://img1.imgtn.bdimg.com/it/u=3533821055,2578418634&fm=23&gp=0.jpg");
//        data.add("http://img2.imgtn.bdimg.com/it/u=1745775257,508697643&fm=23&gp=0.jpg");
//        data.add("http://img4.imgtn.bdimg.com/it/u=948729161,3257619677&fm=23&gp=0.jpg");
//        data.add("http://img3.imgtn.bdimg.com/it/u=266777875,2420215328&fm=23&gp=0.jpg");
//        data.add("http://img0.imgtn.bdimg.com/it/u=915285971,1710943711&fm=23&gp=0.jpg");
//        data.add("http://images.17173.com/2013/jx3//2013/07/08/20130708180316774.gif");

        myViewHolder.iv_img.setImages(data);
    }

    @Override
    public int getItemCount() {
        return mListData == null ? 0 : mListData.size();
    }

    class MyViewHolder extends RecyclerView.ViewHolder {
        AvatarImageView iv_head;
        TextView tv_name;
        TextView tv_content;
        ImageView iv_chat;
        MultiView iv_img;

        public MyViewHolder(View itemView) {
            super(itemView);
            iv_head = (AvatarImageView) itemView.findViewById(R.id.iv_head);
            tv_name = (TextView) itemView.findViewById(R.id.tv_name);
            tv_content = (TextView) itemView.findViewById(R.id.tv_content);
            iv_chat = (ImageView) itemView.findViewById(R.id.iv_chat);
            iv_img = (MultiView) itemView.findViewById(R.id.iv_img);
        }
    }
就是把MultiView当然recycleview里item里的一个子view使用，会不断重复往里面加载数据~不断的上下滑动，item里的九宫图会不断变多~直接去掉item复用也是。。。

**Comment by baoziguo** [comment]
下拉刷新也是一样的，不过第一次确实只绘制了一次，但是我一下拉刷新，就会绘制2次，比如，只有2张图的，我下拉一下，就会变成6张图

**Comment by zhazhaxin** [comment]
if (bbs.pictures.length() > 0) {
                Gson gson = new Gson();
                Type listType = new TypeToken<List<String>>() {}.getType();
                List<String> pics = gson.fromJson(bbs.pictures, listType);
                mMultiView.clear();
                mMultiView.setImages(pics);
            }
这里应该先 clear() 下数据再添加哈。你可以看下我写的 demo 的这个类。https://github.com/llxdaxia/Common/blob/dev/demo/src/main/java/cn/lemon/jcourse/module/bbs/BBSAdapter.java

还推荐你使用 RecyclerView ，我还做了一个库：https://github.com/llxdaxia/RecyclerView
